### ISSUE TITLE
Promise not awaited

### ISSUE THREAD

**Issue by Timmmm** [JRJurman/excalidraw-to-svg#1]
Hi, thanks for the nice project. There are a couple of easy bugs in it though:

In `cli.js` `excalidrawToSVG()` returns a `Promise` but then you don't actually `await` it.

**Comment by JRJurman** [comment]
Thanks for catching this! When the API changed to be Promise based, I hadn't re-verified the cli interface. I should probably write a test to verify that that functionality works 😅.

**Comment by JRJurman** [comment]
This has been resolved as part of v3.0.1
